CREATE USER 'Teletubbies'@'localhost' IDENTIFIED BY 'ab1l';
DROP DATABASE IF EXISTS WHOISNEXT;
CREATE DATABASE WHOISNEXT;
GRANT ALL PRIVILEGES ON WHOISNEXT.* TO 'Teletubbies'@'localhost' WITH GRANT OPTION;
